# Generated by Django 3.0.8 on 2020-11-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=20, verbose_name='фамилия')),
                ('first', models.CharField(max_length=20, verbose_name='имя')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='портрет')),
            ],
            options={
                'ordering': ['last', 'first'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='год выпуска')),
                ('rating', models.FloatField(default=5.0, verbose_name='рейтинг')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='musics/', verbose_name='постер')),
                ('text', models.FileField(blank=True, null=True, upload_to='texts/', verbose_name='текст')),
                ('author', models.ForeignKey(blank=True, help_text='автор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pr1.Author')),
            ],
        ),
    ]
