# Generated by Django 3.0.8 on 2020-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0002_auto_20201206_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pseudonym',
            field=models.CharField(max_length=20, verbose_name='Псевдоним'),
        ),
    ]
