# Generated by Django 3.0.8 on 2020-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0003_auto_20201209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to='descriptions/', verbose_name='Описание'),
        ),
    ]
